# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LWP-Simple-Post
version:      0.04
version_from: lib/LWP/Simple/Post.pm
installdirs:  site
requires:
    LWP:                           0.01
    Test::More:                    0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
